language: java
jdk:
    - oraclejdk8
install: true
script: mvn clean install
notifications:
  irc:
    channels:
      - "chat.freenode.net#52north"
    on_success: always
    on_failure: change
    use_notice: true
    skip_join: false
